##
## EPITECH PROJECT, 2022
## B-CPE-200-NCY-2-1-dante-thomas.dehennault
## File description:
## Makefile
##

all:
	make -C solver
	make -C generator
clean:
	make clean -C solver
	make clean -C generator

fclean:
	make fclean -C solver
	make fclean -C generator

re:
	make re -C solver
	make re -C generator
