/*
** EPITECH PROJECT, 2022
** B-MUL-200-NCY-2-1-myrpg-antoine.khalidy
** File description:
** keyboard
*/

#include "utils/keyboard.h"

touch_t const keyboard[] = {
    {sfKeyEscape, "Escape"},
    {sfKeyTab, "Tab"},
    {sfKeyLeft, "Left"},
    {sfKeyRight, "Right"},
    {sfKeyUp, "Up"},
    {sfKeyDown, "Down"},
    {sfKeyReturn, "Return"},
    {sfKeySpace, "Space"},
    {sfKeyLShift, "LShift"},
    {sfKeyRShift, "RShift"},
    {sfKeyLControl, "LControl"},
    {sfKeyRControl, "RControl"},
    {sfKeyLAlt, "LAlt"},
    {sfKeyRAlt, "RAlt"},
    {sfKeyLBracket, "LBracket"},
    {sfKeyRBracket, "RBracket"},
    {sfKeySemiColon, "SemiColon"},
    {sfKeyComma, "Comma"},
    {sfKeyPeriod, "Period"},
    {sfKeyQuote, "Quote"},
    {sfKeySlash, "Slash"},
    {sfKeyBackSlash, "BackSlash"},
    {sfKeyTilde, "Tilde"},
    {sfKeyEqual, "Equal"},
    {sfKeyDash, "Dash"},
    {sfKeyA, "A"},
    {sfKeyB, "B"},
    {sfKeyC, "C"},
    {sfKeyD, "D"},
    {sfKeyE, "E"},
    {sfKeyF, "F"},
    {sfKeyG, "G"},
    {sfKeyH, "H"},
    {sfKeyI, "I"},
    {sfKeyJ, "J"},
    {sfKeyK, "K"},
    {sfKeyL, "L"},
    {sfKeyM, "M"},
    {sfKeyN, "N"},
    {sfKeyO, "O"},
    {sfKeyP, "P"},
    {sfKeyQ, "Q"},
    {sfKeyR, "R"},
    {sfKeyS, "S"},
    {sfKeyT, "T"},
    {sfKeyU, "U"},
    {sfKeyV, "V"},
    {sfKeyW, "W"},
    {sfKeyX, "X"},
    {sfKeyY, "Y"},
    {sfKeyZ, "Z"},
    {sfKeyNum0, "Num0"},
    {sfKeyNum1, "Num1"},
    {sfKeyNum2, "Num2"},
    {sfKeyNum3, "Num3"},
    {sfKeyNum4, "Num4"},
    {sfKeyNum5, "Num5"},
    {sfKeyNum6, "Num6"},
    {sfKeyNum7, "Num7"},
    {sfKeyNum8, "Num8"},
    {sfKeyNum9, "Num9"},
    {sfKeyF1, "F1"},
    {sfKeyF2, "F2"},
    {sfKeyF3, "F3"},
    {sfKeyF4, "F4"},
    {sfKeyF5, "F5"},
    {sfKeyF6, "F6"},
    {sfKeyF7, "F7"},
    {sfKeyF8, "F8"},
    {sfKeyF9, "F9"},
    {sfKeyF10, "F10"},
    {sfKeyF11, "F11"},
    {sfKeyF12, "F12"},
    {sfKeyF13, "F13"},
    {sfKeyF14, "F14"},
    {sfKeyF15, "F15"},
    {sfKeyPause, "Pause"},
    {sfKeyNumpad0, "Numpad0"},
    {sfKeyNumpad1, "Numpad1"},
    {sfKeyNumpad2, "Numpad2"},
    {sfKeyNumpad3, "Numpad3"},
    {sfKeyNumpad4, "Numpad4"},
    {sfKeyNumpad5, "Numpad5"},
    {sfKeyNumpad6, "Numpad6"},
    {sfKeyNumpad7, "Numpad7"},
    {sfKeyNumpad8, "Numpad8"},
    {sfKeyNumpad9, "Numpad9"},
    {sfKeyAdd, "NumpadAdd"},
    {sfKeySubtract, "NumpadSubtract"},
    {sfKeyMultiply, "NumpadMultiply"},
    {sfKeyDivide, "NumpadDivide"},
    {sfKeyLSystem, "LSystem"},
    {sfKeyRSystem, "RSystem"},
    {sfKeyMenu, "Menu"},
    {sfKeyLBracket, "LBracket"},
    {sfKeyRBracket, "RBracket"},
    {sfKeyDelete, "Delete"},
    {sfKeyEnd, "End"},
    {sfKeyHome, "Home"},
    {sfKeyInsert, "Insert"},
    {sfKeyPageDown, "PageDown"},
    {sfKeyPageUp, "PageUp"},
    {sfKeyUnknown, "Unknown"}
};

char const *get_keyname(sfKeyCode key)
{
    for (int i = 0; keyboard[i].key != sfKeyUnknown; ++i) {
        if (keyboard[i].key == key)
            return keyboard[i].name;
    }
    return "Unknown";
}
