#!/usr/bin/env python3

import sys
import math
from utils import *
from secant import *
from newton import *
from bisection import *

if (len(sys.argv) == 2 and sys.argv[1] == '-h'):
    print("USAGE")
    print("    ./105torus opt a0 a1 a2 a3 a4 n")
    print(" ")
    print("DESCRIPTION")
    print("    opt       method option:")
    print("                  1 for the bisection method")
    print("                  2 for Newton's method")
    print("                  3 for the secant method")
    print("    a[0-4]    coefficients of the equation")
    print("    n         precision (the application of the polynomial to the solution")
    print("              should be smaller than 10ˆ-n)")
    exit(0)
try:
    arg1 = int(sys.argv[1])
    arg2 = int(sys.argv[2])
    arg3 = int(sys.argv[3])
    arg4 = int(sys.argv[4])
    arg5 = int(sys.argv[5])
    arg6 = int(sys.argv[6])
    arg7 = int(sys.argv[7])
except:
    print("Invalid argument")
    exit(84)

if (len(sys.argv) == 8 and arg1 == 1 and arg7 > 0):
    bisection(arg7, arg6, arg5, arg4, arg3, arg2)
elif (len(sys.argv) == 8 and arg1 == 2 and arg7 > 0):
    newton(arg7, arg6, arg5, arg4, arg3, arg2)
elif (len(sys.argv) == 8 and arg1 == 3 and arg7 > 0):
    secant(arg7, arg6, arg5, arg4, arg3, arg2)
else:
   print("Invalid argument")
   exit(84)