#!/usr/bin/env python3

import sys
from math import *
from matrix import *

if (len(sys.argv) == 2 and sys.argv[1] == '-h'):
        print("USAGE")
        print("    ./103cipher message key flag")
        print(" ")
        print("DESCRIPTION")
        print("    message    a message, made of ASCII characters")
        print("    key        the encryption key, made of ASCII characters")
        print("    flag       0 for the message to be encrypted, 1 to be descrypted")
        exit(0)
elif (len(sys.argv) != 4):
        print("invalid argument")
        exit(84)
        
message = sys.argv[1]
key = sys.argv[2]
flag = 0

try:
        flag = int(sys.argv[3])
except:
        print("invalid argument")
        exit(84)


if flag == 0:
        key_matrix = ascii_to_matrix(key)
        message_matrix = ascii_to_matrix(message, len(key_matrix.value[0]))
        print("Key matrix:")
        print(key_matrix)
        print("\nEncrypted message:")
        print(message_matrix.multiply_by(key_matrix).inline())
elif flag == 1:
        key_matrix = ascii_to_matrix(key).reverse()
        message_matrix = inline_to_matrix(message.split(" "), len(key_matrix.value[0]))
        print("Key matrix:")
        print(key_matrix)
        print("\nDecrypted message:")
        print(matrix_to_ascii(message_matrix.multiply_by(key_matrix)))
else:
        print("invalid argument")
        exit(84)
        
